title: Kevin Litchmore
#logo:
description: As a Information Technologies professional, I possess a comprehensive skill set encompassing database design, data modeling, data manipulation, and data analysis. With a strong foundation in industry best practices, I excel in delivering innovative solutions that drive data-driven insights to provide informed decision-making. Throughout my career, I have demonstrated a keen ability to analyze complex data requirements, identify potential data quality issues, and implement strategic solutions to ensure data integrity and reliability. My expertise spans a wide range of technologies, including SQL databases, data warehousing, business intelligence, and cloud-based data platforms.
#show_downloads: 
theme: minimal
skin: classic


  #social_links:
  #  - title: Minima Theme repository at GitHub
  #    icon: github
  #    url: "https://github.com/jekyll/minima"
  #  - title: Jekyll at X (formerly Twitter)
  #    icon: x-twitter
  #    url: "https://x.com/jekyllrb"
